# Generated by Django 5.2.1 on 2025-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_full_name_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Standard Shipping', max_length=50),
        ),
    ]
